allowBuilds:
  '@firebase/util': set this to true or false
  '@scarf/scarf': set this to true or false
  '@tree-sitter-grammars/tree-sitter-yaml': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  nodemon: set this to true or false
  protobufjs: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-json: set this to true or false
