// file: src/modules/renter/renter.model.ts

import { BaseSchemaUtil } from "@/utils/base-schema.utils";
import { model, Schema } from "mongoose";
import type { IRenterProfile } from "./renter.interface";

const renterProfileSchema = BaseSchemaUtil.createSchema<IRenterProfile>({
  userId: {
    type: Schema.Types.ObjectId, // ⚠️ Changed from String to ObjectId
    ref: "User",
    required: true,
    unique: true,
    index: true,
  },

  // ============================================
  // NOTIFICATION PREFERENCES
  // ============================================

  savedRequestsAlerts: {
    type: Boolean,
    default: true,
  },
  emailNotificationsSubscribed: {
    type: Boolean,
    default: true,
  },
  matchNotifications: {
    type: Boolean,
    default: true,
  },
  weeklyReportDigest: {
    type: Boolean,
    default: false,
  },

  // ============================================
  // ACTIVITY METRICS
  // ============================================

  totalPreMarketRequests: {
    type: Number,
    default: 0,
  },
  activePreMarketRequests: {
    type: Number,
    default: 0,
  },
  totalMatches: {
    type: Number,
    default: 0,
  },
  approvedMatches: {
    type: Number,
    default: 0,
  },

  profileCompleteness: {
    type: Number,
    default: 0,
    min: 0,
    max: 100,
  },

  // ============================================
  // REFERRAL TRACKING
  // ============================================

  /**
   * Quick access to referrer info
   * Duplicated from User model for performance
   */
  referrerName: String,
  referrerEmail: String,

  /**
   * Track if renter has acknowledged auto-generated password
   */
  acknowledgedAutoPassword: {
    type: Boolean,
    default: false,
  },
});

// ============================================
// INDEXES
// ============================================

renterProfileSchema.index({ userId: 1, emailNotificationsSubscribed: 1 });
renterProfileSchema.index({ createdAt: -1 });

// ============================================
// MIDDLEWARE
// ============================================

/**
 * Auto-populate userId with user details
 */
renterProfileSchema.pre(/^find/, function (this: any) {
  if (this.getOptions().populateUser) {
    this.populate({
      path: "userId",
      select:
        "fullName email phone referredBy referredByRole passwordAutoGenerated",
    });
  }
});

export const RenterProfile = model<IRenterProfile>(
  "RenterProfile",
  renterProfileSchema
);
