// file: src/modules/renter/renter.type.ts

/**
 * Renter Registration Payload (Complete registration)
 * Includes user fields + referral
 */
export type RenterRegisterPayload = {
  // User fields
  email: string;
  password?: string; // Optional for admin referral
  fullName: string;
  phoneNumber?: string;

  // Referral
  referralCode?: string;
};

/**
 * Create renter profile payload (INTERNAL)
 */
export type CreateRenterProfilePayload = {
  referrerName?: string;
  referrerEmail?: string;
  acknowledgedAutoPassword?: boolean;
};

/**
 * Renter registration response (User + Profile)
 */
export type RenterRegistrationResponse = {
  user: {
    _id: string;
    email: string;
    fullName: string;
    role: string;
    referredBy?: string;
    referredByRole?: string;
    passwordAutoGenerated: boolean;
    mustChangePassword: boolean;
  };
  profile: RenterProfileResponse;
  tokens: {
    accessToken: string;
    refreshToken: string;
    expiresIn: string;
  };
  passwordAutoGenerated?: boolean; // For frontend to show notice
};

/**
 * Renter profile response
 */
export type RenterProfileResponse = {
  _id: string;
  userId: string;
  savedRequestsAlerts: boolean;
  emailNotificationsSubscribed: boolean;
  matchNotifications: boolean;
  weeklyReportDigest: boolean;
  totalPreMarketRequests: number;
  activePreMarketRequests: number;
  totalMatches: number;
  approvedMatches: number;
  profileCompleteness: number;
  referrerName?: string;
  referrerEmail?: string;
  acknowledgedAutoPassword?: boolean;
  createdAt: Date;
  updatedAt: Date;
};

/**
 * Update renter notification preferences
 */
export type UpdateRenterNotificationsPayload = {
  savedRequestsAlerts?: boolean;
  emailNotificationsSubscribed?: boolean;
  matchNotifications?: boolean;
  weeklyReportDigest?: boolean;
};

/**
 * Renter stats response
 */
export type RenterStatsResponse = {
  totalPreMarketRequests: number;
  activePreMarketRequests: number;
  totalMatches: number;
  approvedMatches: number;
  profileCompleteness: number;
};
