// file: src/services/email.types.ts

export type IEmailRecipient = string | { email: string; name?: string };

export type IEmailRecipients = IEmailRecipient | IEmailRecipient[];

export type IEmailPriority = "high" | "normal" | "low";

export interface IEmailAttachment {
  filename: string;
  content: Buffer | string;
  contentType?: string;
  contentDisposition?: "attachment" | "inline";
}

export interface IEmailOptions {
  to: IEmailRecipient | IEmailRecipient[];
  cc?: IEmailRecipient | IEmailRecipient[];
  bcc?: IEmailRecipient | IEmailRecipient[];
  from?: { name: string; email: string };
  replyTo?: string;
  subject: string;
  html: string;
  text?: string;
  priority?: IEmailPriority;
  attachments?: IEmailAttachment[];
  headers?: Record<string, string>;
  inReplyTo?: string;
  references?: string[];
  tags?: string[];
  metadata?: Record<string, string>;
}

export interface IEmailResponse {
  messageId: string;
  response: string;
  accepted?: string[];
  rejected?: string[];
  timestamp: Date;
  retries: number;
  error?: Error | null;
}

export interface IEmailResult {
  success: boolean;
  messageId?: string;
  error?: string | Error;
  timestamp: Date;
  attempt: number;
  maxAttempts: number;
}

export interface IPostmarkConfig {
  apiToken: string;
  messageStream: "outbound" | "broadcast";
  sandboxMode: boolean;
  serverUrl: string;
  timeout: number;
}

export interface IEmailConfig {
  postmark: IPostmarkConfig;
  from: { name: string; email: string };
  replyTo?: string;
  logoUrl?: string;
  brandColor?: string;
  adminEmail: string;
  maxRetries: number;
  retryDelayMs: number;
}

export interface IEmailTransporter {
  send(options: IEmailOptions): Promise<IEmailResponse>;
  verify(): Promise<boolean>;
  close(): Promise<void>;
  isConnectionActive(): boolean;
}

export enum EmailTemplate {
  WELCOME = "welcome",
  EMAIL_VERIFICATION = "email_verification",
  PASSWORD_RESET = "password_reset",
  PASSWORD_CHANGED = "password_changed",
  EMAIL_CHANGED = "email_changed",
  ACCOUNT_DELETED = "account_deleted",
  LOGIN_ALERT = "login_alert",
}

export interface IEmailTemplateVariables {
  userName: string;
  email: string;
  userType: "Agent" | "Renter";
  currentYear: number;
  loginLink?: string;
  verificationCode?: string;
  expiresIn?: string;
  resetLink?: string;
  newEmail?: string;
  [key: string]: any;
}

export interface ITemplateRenderRequest {
  template: EmailTemplate;
  variables: IEmailTemplateVariables;
}

export interface ITemplateRenderResult {
  subject: string;
  html: string;
  text?: string;
}

export type UserType = "Agent" | "Renter" | "Admin";

export interface IEmailVerificationPayload {
  to: string;
  userName: string;
  userType: UserType | string;
  verificationCode: string;
  expiresIn: number;
}

export interface IPasswordResetPayload {
  to: string;
  userName: string;
  resetLink: string;
  expiresIn: number;
}

export interface IPasswordChangedPayload {
  to: string;
  userName: string;
  timestamp: Date;
}

/**
 * Welcome email payload
 */
export interface IWelcomeRegisteredAgentDetails {
  fullName?: string;
  title?: string;
  brokerage?: string;
}

export interface IWelcomeEmailPayload {
  to: string;
  userName: string;
  userType: "Agent" | "Renter" | string;
  loginLink: string;
  isPasswordAutoGenerated?: boolean;
  temporaryPassword?: string;
  registeredAgent?: IWelcomeRegisteredAgentDetails;
}

export interface IAgentActivatedByAdminEmailPayload {
  to: string;
  agentName: string;
  dashboardLink: string;
}
export interface IPasswordResetPayload {
  to: string;
  userName: string;
  resetLink: string;
  expiresIn: number;
}

export interface IPasswordChangedPayload {
  to: string;
  userName: string;
  timestamp: Date;
  supportEmail?: string;
}

export interface IEmailChangePayload {
  to: string; // New email
  userName: string;
  newEmail: string;
  oldEmail: string;
}

export interface IAccountDeletedPayload {
  to: string;
  userName: string | undefined;
}

export interface IEmailError extends Error {
  code?: string;
  statusCode?: number;
  response?: any;
  retry?: boolean;
}

export interface IEmailValidationError extends Error {
  field: string;
  value: any;
}

export interface IEmailLog {
  messageId: string;
  to: string[];
  subject: string;
  template?: EmailTemplate;
  status: "pending" | "sent" | "failed";
  error?: string;
  attempts: number;
  createdAt: Date;
  sentAt?: Date;
  response?: any;
}

export interface IEmailServiceOptions {
  config: IEmailConfig;
  enableLogging?: boolean;
  maxConcurrentEmails?: number;
  queue?: {
    enabled: boolean;
    maxQueueSize: number;
  };
}

export function isEmailRecipient(value: any): value is IEmailRecipient {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof value.email === "string"
  );
}

export function isEmailRecipientArray(value: any): value is IEmailRecipient[] {
  return Array.isArray(value) && value.every(isEmailRecipient);
}

export function isEmailAttachment(value: any): value is IEmailAttachment {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof value.filename === "string"
  );
}

export function normalizeRecipients(
  recipients: IEmailRecipient | IEmailRecipient[]
): IEmailRecipient[] {
  return Array.isArray(recipients) ? recipients : [recipients];
}

export interface IAdminReferralEmailPayload {
  to: string;
  userName: string;
  temporaryPassword:
    | string
    | {
        password: string;
        expiresInHours: number;
        mustChangeOnLogin: boolean;
      };
  loginLink: string;
  accountType?: "Renter" | "Agent" | "Admin";
  passwordExpiresAt?: Date;
}
