// file: src/services/email.types.ts

/**
 * Complete TypeScript interfaces and types for Email Service
 * Using NodeMailer SMTP transport
 * ✅ Full type-safety
 * ✅ Extensible design
 * ✅ SOLID principles
 */

// ============================================
// EMAIL CONFIGURATION TYPES
// ============================================

/**
 * SMTP Configuration Interface
 * Supports multiple SMTP providers (Gmail, Brevo, AWS SES, etc.)
 */
export interface ISmtpConfig {
  host: string;
  port: number;
  secure: boolean; // true for 465, false for other ports
  auth: {
    user: string;
    pass: string;
  };
  pool?: {
    maxConnections: number;
    maxMessages: number;
    rateDelta: number; // Rate delta (ms)
    rateLimit: number; // Max 3 emails per 10s = 3 messages per 10000ms
  };
  logger?: boolean;
  debug?: boolean;
}

/**
 * Email Service Configuration
 * Contains SMTP config + service-level options
 */
export interface IEmailConfig {
  smtp: ISmtpConfig;
  from: {
    name: string;
    email: string;
  };
  replyTo?: string;
  logoUrl?: string;
  brandColor?: string;
  maxRetries: number;
  retryDelayMs: number;
}

// ============================================
// EMAIL TRANSPORT INTERFACE
// ============================================

/**
 * Abstract email transporter interface
 * Allows swapping between NodeMailer, SendGrid, or other providers
 */
export interface IEmailTransporter {
  send(options: IEmailOptions): Promise<IEmailResponse>;
  verify(): Promise<boolean>;
  close(): Promise<void>;
}

// ============================================
// EMAIL PAYLOAD TYPES
// ============================================

/**
 * Email recipient
 */
export interface IEmailRecipient {
  email: string;
  name?: string;
}

/**
 * Email attachment
 */
export interface IEmailAttachment {
  filename: string;
  content?: Buffer | string;
  path?: string;
  contentType?: string;
}

/**
 * Core email options for sending
 */
export interface IEmailOptions {
  to: IEmailRecipient | IEmailRecipient[];
  cc?: IEmailRecipient | IEmailRecipient[];
  bcc?: IEmailRecipient | IEmailRecipient[];
  subject: string;
  html: string;
  text?: string;
  from?: {
    name: string;
    email: string;
  };
  replyTo?: string;
  attachments?: IEmailAttachment[];
  headers?: Record<string, string>;
  inReplyTo?: string;
  references?: string[];
  priority?: "high" | "normal" | "low";
}

/**
 * Email response after sending
 */
export interface IEmailResponse {
  messageId: string;
  response: string;
  accepted?: string[];
  rejected?: string[];
  pending?: string[];
  error?: Error | null;
  timestamp: Date;
  retries: number;
}

/**
 * Email sending result
 */
export interface IEmailResult {
  success: boolean;
  messageId?: string;
  error?: string | Error;
  timestamp: Date;
  attempt: number;
  maxAttempts: number;
}

// ============================================
// EMAIL TEMPLATE TYPES
// ============================================

/**
 * Template types for different email categories
 */
export enum EmailTemplate {
  WELCOME = "welcome",
  EMAIL_VERIFICATION = "email_verification",
  PASSWORD_RESET = "password_reset",
  PASSWORD_CHANGED = "password_changed",
  EMAIL_CHANGED = "email_changed",
  ACCOUNT_DELETED = "account_deleted",
  LOGIN_ALERT = "login_alert",
}

/**
 * Common template variables
 */
export interface IEmailTemplateVariables {
  userName: string;
  email: string;
  userType: "Agent" | "Renter";
  currentYear: number;
  loginLink?: string;
  verificationCode?: string;
  expiresIn?: string;
  resetLink?: string;
  newEmail?: string;
  [key: string]: any; // Allow custom variables
}

/**
 * Template rendering request
 */
export interface ITemplateRenderRequest {
  template: EmailTemplate;
  variables: IEmailTemplateVariables;
}

/**
 * Template rendering result
 */
export interface ITemplateRenderResult {
  subject: string;
  html: string;
  text?: string;
}

// ============================================
// USER EMAIL TYPES
// ============================================

/**
 * User type discriminator
 */
export type UserType = "Agent" | "Renter" | "Admin";

/**
 * Email verification payload
 */
export interface IEmailVerificationPayload {
  to: string;
  userName: string | undefined;
  userType: UserType | string;
  verificationCode: string;
  expiresIn: string;
}

/**
 * Welcome email payload
 */
export interface IWelcomeEmailPayload {
  to: string;
  userName: string;
  userType: "Agent" | "Renter";
  loginLink: string;
  isPasswordAutoGenerated?: boolean;
  temporaryPassword?: string;
}

/**
 * Password reset request payload
 */
export interface IPasswordResetPayload {
  to: string;
  userName: string;
  resetLink: string;
  expiresIn: string;
}

/**
 * Password changed confirmation payload
 */
export interface IPasswordChangedPayload {
  to: string;
  userName: string;
  timestamp: Date;
  supportEmail?: string;
}

/**
 * Email change confirmation payload
 */
export interface IEmailChangePayload {
  to: string; // New email
  userName: string;
  newEmail: string;
  oldEmail: string;
}

// ============================================
// ERROR TYPES
// ============================================

/**
 * Email service error
 */
export interface IEmailError extends Error {
  code?: string;
  statusCode?: number;
  response?: any;
  retry?: boolean;
}

/**
 * Email validation error
 */
export interface IEmailValidationError extends Error {
  field: string;
  value: any;
}

// ============================================
// LOGGING TYPES
// ============================================

/**
 * Email log entry
 */
export interface IEmailLog {
  messageId: string;
  to: string[];
  subject: string;
  template?: EmailTemplate;
  status: "pending" | "sent" | "failed";
  error?: string;
  attempts: number;
  createdAt: Date;
  sentAt?: Date;
  response?: any;
}

// ============================================
// SERVICE INITIALIZATION
// ============================================

/**
 * Email service initialization options
 */
export interface IEmailServiceOptions {
  config: IEmailConfig;
  enableLogging?: boolean;
  maxConcurrentEmails?: number;
  queue?: {
    enabled: boolean;
    maxQueueSize: number;
  };
}

// ============================================
// TYPE GUARDS
// ============================================

/**
 * Check if value is IEmailRecipient
 */
export function isEmailRecipient(value: any): value is IEmailRecipient {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof value.email === "string"
  );
}

/**
 * Check if value is IEmailRecipient array
 */
export function isEmailRecipientArray(value: any): value is IEmailRecipient[] {
  return Array.isArray(value) && value.every(isEmailRecipient);
}

/**
 * Check if value is IEmailAttachment
 */
export function isEmailAttachment(value: any): value is IEmailAttachment {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof value.filename === "string"
  );
}

/**
 * Normalize recipients to array format
 */
export function normalizeRecipients(
  recipients: IEmailRecipient | IEmailRecipient[]
): IEmailRecipient[] {
  return Array.isArray(recipients) ? recipients : [recipients];
}

/**
 * Admin referral email payload
 */
export interface IAdminReferralEmailPayload {
  to: string;
  userName: string;
  temporaryPassword:
    | string
    | {
        password: string;
        expiresInHours: number;
        mustChangeOnLogin: boolean;
      };
  loginLink: string;
}
