// file: src/services/email.types.ts

export type IEmailRecipient = string | { email: string; name?: string };

export type IEmailRecipients = IEmailRecipient | IEmailRecipient[];

export type IEmailPriority = "high" | "normal" | "low";

export type IEmailAttachment = {
  filename: string;
  content: Buffer | string;
  contentType?: string;
  contentDisposition?: "attachment" | "inline";
  contentId?: string;
};

export type IEmailOptions = {
  to: IEmailRecipient | IEmailRecipient[];
  cc?: IEmailRecipient | IEmailRecipient[];
  bcc?: IEmailRecipient | IEmailRecipient[];
  from?: { name: string; email: string };
  replyTo?: string;
  subject: string;
  html: string;
  text?: string;
  priority?: IEmailPriority;
  attachments?: IEmailAttachment[];
  headers?: Record<string, string>;
  inReplyTo?: string;
  references?: string[];
  tags?: string[];
  metadata?: Record<string, string>;
};

export type IEmailResponse = {
  messageId: string;
  response: string;
  accepted?: string[];
  rejected?: string[];
  timestamp: Date;
  retries: number;
  error?: Error | null;
};

export type IEmailResult = {
  success: boolean;
  messageId?: string;
  error?: string | Error;
  timestamp: Date;
  attempt: number;
  maxAttempts: number;
};

export type IPostmarkConfig = {
  apiToken: string;
  messageStream: "outbound" | "broadcast";
  sandboxMode: boolean;
  serverUrl: string;
  timeout: number;
};

export type IEmailConfig = {
  postmark: IPostmarkConfig;
  from: { name: string; email: string };
  replyTo?: string;
  logoUrl?: string;
  brandColor?: string;
  adminEmail: string;
  maxRetries: number;
  retryDelayMs: number;
};

export type IEmailTransporter = {
  send: (options: IEmailOptions) => Promise<IEmailResponse>;
  verify: () => Promise<boolean>;
  close: () => Promise<void>;
  isConnectionActive: () => boolean;
};

export enum EmailTemplate {
  WELCOME = "welcome",
  EMAIL_VERIFICATION = "email_verification",
  PASSWORD_RESET = "password_reset",
  PASSWORD_CHANGED = "password_changed",
  EMAIL_CHANGED = "email_changed",
  ACCOUNT_DELETED = "account_deleted",
  LOGIN_ALERT = "login_alert",
}

export type IEmailTemplateVariables = {
  userName: string;
  email: string;
  userType: "Agent" | "Renter";
  currentYear: number;
  loginLink?: string;
  verificationCode?: string;
  expiresIn?: string;
  resetLink?: string;
  newEmail?: string;
  [key: string]: any;
};

export type ITemplateRenderRequest = {
  template: EmailTemplate;
  variables: IEmailTemplateVariables;
};

export type ITemplateRenderResult = {
  subject: string;
  html: string;
  text?: string;
};

export type UserType = "Agent" | "Renter" | "Admin";

export type IEmailVerificationPayload = {
  to: string;
  userName: string;
  userType: UserType | string;
  verificationCode: string;
  expiresIn: number;
};

/**
 * Welcome email payload
 */
export type IWelcomeRegisteredAgentDetails = {
  fullName?: string;
  title?: string;
  brokerage?: string;
};

export type IWelcomeEmailPayload = {
  to: string;
  userName: string;
  userType: "Agent" | "Renter" | string;
  loginLink: string;
  isPasswordAutoGenerated?: boolean;
  temporaryPassword?: string;
  registeredAgent?: IWelcomeRegisteredAgentDetails;
};

export type IMovingDiscountCodesEmailPayload = {
  to: string;
  renterName: string;
};

export type IAgentActivatedByAdminEmailPayload = {
  to: string;
  agentName: string;
  dashboardLink: string;
};
export type IPasswordResetPayload = {
  to: string;
  userName: string;
  resetLink: string;
  expiresIn: number;
};

export type IPasswordChangedPayload = {
  to: string;
  userName: string;
  timestamp: Date;
  supportEmail?: string;
};

export type IEmailChangePayload = {
  to: string; // New email
  userName: string;
  newEmail: string;
  oldEmail: string;
};

export type IAccountDeletedPayload = {
  to: string;
  userName: string | undefined;
};

export type IEmailError = {
  code?: string;
  statusCode?: number;
  response?: any;
  retry?: boolean;
} & Error;

export type IEmailValidationError = {
  field: string;
  value: any;
} & Error;

export type IEmailLog = {
  messageId: string;
  to: string[];
  subject: string;
  template?: EmailTemplate;
  status: "pending" | "sent" | "failed";
  error?: string;
  attempts: number;
  createdAt: Date;
  sentAt?: Date;
  response?: any;
};

export type IEmailServiceOptions = {
  config: IEmailConfig;
  enableLogging?: boolean;
  maxConcurrentEmails?: number;
  queue?: {
    enabled: boolean;
    maxQueueSize: number;
  };
};

export function isEmailRecipient(value: any): value is IEmailRecipient {
  return (
    typeof value === "object"
    && value !== null
    && typeof value.email === "string"
  );
}

export function isEmailRecipientArray(value: any): value is IEmailRecipient[] {
  return Array.isArray(value) && value.every(isEmailRecipient);
}

export function isEmailAttachment(value: any): value is IEmailAttachment {
  return (
    typeof value === "object"
    && value !== null
    && typeof value.filename === "string"
  );
}

export function normalizeRecipients(
  recipients: IEmailRecipient | IEmailRecipient[],
): IEmailRecipient[] {
  return Array.isArray(recipients) ? recipients : [recipients];
}

export type IAdminReferralEmailPayload = {
  to: string;
  userName: string;
  temporaryPassword:
    | string
    | {
      password: string;
      expiresInHours: number;
      mustChangeOnLogin: boolean;
    };
  loginLink: string;
  accountType?: "Renter" | "Agent" | "Admin";
  passwordExpiresAt?: Date;
};
