// file: src/modules/auth/auth.type.ts

import type { UserResponse } from "../user/user.type";

/**
 * Register Payload - ONLY common fields
 * Agent-specific fields removed
 */
export type RegisterPayload = {
  email: string;
  password?: string; // Optional for admin referral
  fullName: string;
  phoneNumber?: string;
  role: string;

  // Referral (common for all)
  referralCode?: string;
};

export type LoginPayload = {
  email: string;
  password: string;
};

export type JWTTokens = {
  accessToken: string;
  refreshToken: string;
  expiresIn: string;
};

/**
 * Auth Service Response (UPDATED)
 * Service layer returns both tokens
 */
export type AuthServiceResponse = {
  user: UserResponse;
  tokens: JWTTokens;
  mustChangePassword?: boolean;
  referralCode?: string; // For agents
  passwordAutoGenerated?: boolean; // For admin-referred renters
};

/**
 * Auth Token Response (for API responses)
 */
export type AuthTokenResponse = {
  accessToken: string;
  refreshToken: string;
  expiresIn: string;
};

/**
 * Auth Controller Response (NEW)
 * Controller layer returns only access token in JSON
 */
export type AuthControllerResponse = {
  user: UserResponse;
  accessToken: string; // Only access token in JSON
  expiresIn: string;
  mustChangePassword?: boolean;
  referralCode?: string;
  passwordAutoGenerated?: boolean;
};

/**
 * Change password payload
 */
export type ChangePasswordPayload = {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
};
