// file: src/modules/user/user.repository.ts

import { logger } from "@/middlewares/pino-logger";
import { BaseRepository } from "@/modules/base/base.repository";
import { ObjectId } from "mongoose";
import type { IUser } from "./user.interface";
import { RefreshTokenBlacklist, User } from "./user.model";

/**
 * User Repository - Extended with referral operations
 */
export class UserRepository extends BaseRepository<IUser> {
  constructor() {
    super(User);
  }

 
  async findByEmail(email: string): Promise<IUser | null> {
    return this.model
      .findOne({ email: email.toLowerCase(), isDeleted: false })
      .exec();
  }

  
  async findByEmailWithPassword(email: string): Promise<IUser | null> {
    return this.model
      .findOne({ email: email.toLowerCase(), isDeleted: false })
      .select("+password")
      .exec();
  }

  async findByVerificationToken(token: string): Promise<IUser | null> {
    return this.model
      .findOne({
        emailVerificationToken: token,
        isDeleted: false,
      })
      .select("+emailVerificationToken +emailVerificationExpiresAt")
      .exec();
  }

 
  async findByReferralCode(referralCode: string): Promise<IUser | null> {
    return this.model
      .findOne({
        referralCode,
        isDeleted: false,
        role: { $in: ["Admin", "Agent"] }, 
      })
      .exec();
  }

  async generateUniqueReferralCode(prefix: string): Promise<string> {
    const crypto = require("crypto");
    let isUnique = false;
    let referralCode = "";

    while (!isUnique) {
      const randomPart = crypto
        .randomBytes(6)
        .toString("base64")
        .replace(/[^a-zA-Z0-9]/g, "")
        .substring(0, 8)
        .toUpperCase();

      referralCode = `${prefix}-${randomPart}`;

      const existing = await this.model.findOne({ referralCode }).exec();
      if (!existing) {
        isUnique = true;
      }
    }

    return referralCode;
  }

 
  async incrementReferralCount(userId: string): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(
        userId,
        {
          $inc: { totalReferrals: 1 },
          $set: {
            firstReferralUsedAt: new Date(),
          },
        },
        { new: true }
      )
      .exec();
  }

  async updateReferralCount(
    userId: string,
    count: number
  ): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(userId, { totalReferrals: count }, { new: true })
      .exec();
  }

  async getReferredUsers(referrerId: string): Promise<IUser[]> {
    return this.model
      .find({
        referredBy: referrerId,
        isDeleted: false,
      })
      .sort({ createdAt: -1 })
      .exec();
  }

  async countReferredUsers(referrerId: string): Promise<number> {
    return this.model
      .countDocuments({
        referredBy: referrerId,
        isDeleted: false,
      })
      .exec();
  }


  async findByRole(role: string): Promise<IUser[]> {
    return this.model.find({ role, isDeleted: false }).exec();
  }

  async findByAccountStatus(status: string): Promise<IUser[]> {
    return this.model.find({ accountStatus: status, isDeleted: false }).exec();
  }

  async searchUsers(searchTerm: string): Promise<IUser[]> {
    const regex = new RegExp(searchTerm, "i");
    return this.model
      .find({
        $or: [{ email: regex }, { fullName: regex }],
        isDeleted: false,
      })
      .exec();
  }

  async markEmailAsVerified(userId: string): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(
        userId,
        {
          emailVerified: true,
          emailVerificationToken: undefined,
          emailVerificationExpiresAt: undefined,
          accountStatus: "active",
        },
        { new: true }
      )
      .exec();
  }

  async updateVerificationToken(
    userId: string,
    data: {
      emailVerificationToken?: string;
      emailVerificationExpiresAt?: Date;
    }
  ): Promise<IUser | null> {
    return this.model.findByIdAndUpdate(userId, data, { new: true }).exec();
  }

  async updatePassword(
    userId: string,
    hashedPassword: string
  ): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(
        userId,
        {
          password: hashedPassword,
          passwordChangedAt: new Date(),
          mustChangePassword: false,
          passwordAutoGenerated: false,
        },
        { new: true }
      )
      .exec();
  }

  async updateLastLogin(userId: string): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(userId, { lastLoginAt: new Date() }, { new: true })
      .exec();
  }


  async restoreUser(userId: string): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(
        userId,
        {
          isDeleted: false,
          deletedAt: undefined,
          deletedBy: undefined,
          accountStatus: "active",
        },
        { new: true }
      )
      .exec();
  }

  async softDeleteUser(
    userId: string,
    deletedBy?: string
  ): Promise<IUser | null> {
    return this.model
      .findByIdAndUpdate(
        userId,
        {
          isDeleted: true,
          deletedAt: new Date(),
          deletedBy: deletedBy || undefined,
          accountStatus: "inactive",
        },
        { new: true }
      )
      .exec();
  }

  async findDeletedUsers(): Promise<IUser[]> {
    return this.model.find({ isDeleted: true }).exec();
  }

  async permanentlyDeleteUser(userId: string): Promise<any> {
    return this.model.deleteOne({ _id: userId }).exec();
  }

  async countByRole(role: string): Promise<number> {
    return this.model.countDocuments({ role, isDeleted: false }).exec();
  }

  async countActiveUsers(): Promise<number> {
    return this.model
      .countDocuments({ accountStatus: "active", isDeleted: false })
      .exec();
  }

 
  async findByIdWithPassword(userId: string): Promise<IUser | null> {
    return this.model.findById(userId).select("+password").exec();
  }

  async deleteAllRefreshTokens(userId: string): Promise<number> {
    try {
      const result = await RefreshTokenBlacklist.deleteMany({
        userId: userId,
      });

      return result.deletedCount || 0;
    } catch (error) {
      logger.error({ userId, error }, "Error deleting refresh tokens");
      throw error;
    }
  }

  async findRenterWithReferrer(renterId: string | ObjectId): Promise<any> {
    return this.model
      .findById(renterId)
      .populate({
        path: "referredByAgentId",
        select: "fullName email phoneNumber referralCode _id",
        options: { lean: true },
      })
      .populate({
        path: "referredByAdminId",
        select: "fullName email referralCode _id",
        options: { lean: true },
      })
      .exec();
  }
}
