import { ACCOUNT_STATUS } from "@/constants";
import { ROLES } from "@/constants/app.constants";
import type { Document, Types } from "mongoose";

/**
 * Base User Document Interface
 * ✅ Only data properties, methods are separate
 */
export interface IUser extends Document {
  // CORE FIELDS
  _id: Types.ObjectId;
  email: string;
  password?: string; // Selected with .select("+password")
  phoneNumber?: string;
  fullName: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  accountStatus: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];

  // PROFILE FIELDS
  /**
   * User's profile image URL from S3
   */
  profileImageUrl?: string | null;

  // REFERRAL SYSTEM
  referralCode?: string;
  referredBy?: Types.ObjectId | IUser;
  referredByRole?: "Agent" | "Admin";
  passwordAutoGenerated: boolean;
  firstReferralUsedAt?: Date;
  totalReferrals: number;

  // EMAIL VERIFICATION
  emailVerified: boolean;
  emailVerificationToken?: string;
  emailVerificationExpiresAt?: Date;

  // ACTIVITY TRACKING
  lastLoginAt?: Date;
  passwordChangedAt?: Date;
  mustChangePassword: boolean;

  // SOFT DELETE
  isDeleted: boolean;
  deletedAt?: Date;
  deletedBy?: Types.ObjectId | IUser;

  // TIMESTAMPS (from BaseSchemaUtil)
  createdAt: Date;
  updatedAt: Date;

  // Virtual fields (computed, not stored)
  referralLink?: string | null;
  canRefer?: boolean;

  // Instance methods (functions, not data)
  isReferredByAdmin(): boolean;
  isReferredByAgent(): boolean;
  needsPasswordChange(): boolean;
}

/**
 * IAgentProfile - Agent-specific profile data
 */
export interface IAgentProfile extends Document {
  userId: Types.ObjectId | string;
  licenseNumber: string;
  brokerageName: string;
  verificationStatus: "pending" | "verified" | "rejected";
  verificationDocuments?: string[];
  hasGrantAccess: boolean;
  grantAccessGivenBy?: Types.ObjectId | string;
  grantAccessDate?: Date;
  isSuspended: boolean;
  suspensionReason?: string;
  suspendedAt?: Date;
  suspendedBy?: Types.ObjectId | string;
  specializations?: string[];
  bio?: string;
  profileCompleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * User Statistics (denormalized)
 */
export interface IUserStats {
  agentStats?: {
    totalRequests: number;
    grantAccessStatus: "pending" | "granted" | "denied";
    verificationStatus: "pending" | "verified" | "rejected";
    isSuspended: boolean;
  };
  renterStats?: {
    activeRequests: number;
    totalSavedRequests: number;
    totalRequests: number;
  };
}

/**

Password Reset OTP Document Interface
*/
export interface IPasswordResetOTP extends Document {
  userId: string;
  otp: string;
  expiresAt: Date;
  attempts: number;
  maxAttempts: number;
  isUsed: boolean;
  usedAt?: Date;
  createdAt: Date;
}

// 🔑 REFRESH TOKEN BLACKLIST
/**
 * IRefreshTokenBlacklist - Invalidated tokens
 * Used for logout and security operations
 */
export interface IRefreshTokenBlacklist extends Document {
  userId: Types.ObjectId | string;
  token: string;
  expiresAt: Date;
  reason: "password_change" | "security_incident" | "admin_action";
  createdAt: Date;
  updatedAt?: Date;
}
