import type { Document, Types } from "mongoose";

/**
 * Base User Document Interface
 * ✅ Only data properties, methods are separate
 */
export interface IUser extends Document {
  _id: Types.ObjectId;
  email: string;
  password?: string;
  phoneNumber?: string; // Alias
  fullName: string;
  role: ROLES;
  accountStatus: ACCOUNT_STATUS;

  // Referral System
  referralCode?: string;
  referredBy?: Types.ObjectId | IUser;
  referredByRole?: ROLES.ADMIN | ROLES.AGENT;
  passwordAutoGenerated: boolean;
  firstReferralUsedAt?: Date;
  totalReferrals: number;

  // Email Verification
  emailVerified: boolean;
  emailVerificationToken?: string;
  emailVerificationExpiresAt?: Date;

  // Activity
  lastLoginAt?: Date;
  passwordChangedAt?: Date;
  mustChangePassword: boolean;

  // Soft Delete
  isDeleted: boolean;
  deletedAt?: Date;
  deletedBy?: Types.ObjectId | IUser;

  // Timestamps (from BaseSchemaUtil)
  createdAt: Date;
  updatedAt: Date;

  // Virtual fields (computed, not stored)
  referralLink?: string | null;
  canRefer?: boolean;

  // Instance methods (functions, not data)
  isReferredByAdmin(): boolean;
  isReferredByAgent(): boolean;
  needsPasswordChange(): boolean;
}

/**
 * User Statistics (denormalized)
 */
export interface IUserStats {
  agentStats?: {
    totalRequests: number;
    grantAccessStatus: "pending" | "granted" | "denied";
    verificationStatus: "pending" | "verified" | "rejected";
    isSuspended: boolean;
  };
  renterStats?: {
    activeRequests: number;
    totalSavedRequests: number;
    totalRequests: number;
  };
}

/**
 *Agent Profile Document Interface
 */
export interface IAgentProfile extends Document {
  userId: string;
  licenseNumber: string;
  brokerageName: string;
  verificationStatus: "pending" | "verified" | "rejected";
  verificationDocuments?: string[];
  hasGrantAccess: boolean;
  grantAccessGivenBy?: string;
  grantAccessDate?: Date;
  isSuspended: boolean;
  suspensionReason?: string;
  suspendedAt?: Date;
  suspendedBy?: string;
  specializations?: string[];
  bio?: string;
  profileCompleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**

Renter Profile Document Interface
*/
export interface IRenterProfile extends Document {
  userId: string;
  preferredLocations?: string[];
  budgetMin?: number;
  budgetMax?: number;
  minBedrooms?: number;
  maxBedrooms?: number;
  petPreferences?: string;
  moveInFlexibilityWeeks: number;
  profileCompleted: boolean;
  profileCompletionPercentage: number;
  activeRequestsCount: number;
  totalSavedRequests: number;
  preferencesUpdatedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

/**

Password Reset OTP Document Interface
*/
export interface IPasswordResetOTP extends Document {
  userId: string;
  otp: string;
  expiresAt: Date;
  attempts: number;
  maxAttempts: number;
  isUsed: boolean;
  usedAt?: Date;
  createdAt: Date;
}
