// file: src/modules/user/user.model.ts

import { ACCOUNT_STATUS, ROLES } from "@/constants/app.constants";
import { BaseSchemaUtil } from "@/utils/base-schema.utils";
import { model, Query, Schema } from "mongoose";
import type { IUser } from "./user.interface";

const userSchema = BaseSchemaUtil.createSchema<IUser>({
  ...BaseSchemaUtil.mergeDefinitions(
    BaseSchemaUtil.emailField(true),
    BaseSchemaUtil.passwordField(),
    BaseSchemaUtil.phoneField(),
    {
      fullName: {
        type: String,
        required: true,
        trim: true,
        index: true,
      },
      role: {
        type: String,
        enum: Object.values(ROLES),
        required: true,
        index: true,
      },
      accountStatus: {
        type: String,
        enum: Object.values(ACCOUNT_STATUS),
        default: ACCOUNT_STATUS.PENDING,
        index: true,
      },

      // PROFILE FIELDS

      /**
       * User's profile image URL
       * - Public URL from Hetzner S3
       * - Stored for all user types (Admin, Agent, Renter)
       * - Can be updated/deleted by user
       */
      profileImageUrl: {
        type: String,
        default: null,
        sparse: true,
        index: true,
      },

      // 🔗 REFERRAL SYSTEM FIELDS
      /**
       * Permanent referral code for Admin and Agent roles
       * - Generated once during registration/seeding
       * - Used to track referred renters
       * - Only applicable for ADMIN and AGENT roles
       */
      referralCode: {
        type: String,
        unique: true,
        sparse: true, // Only Admin/Agent have codes
        index: true,
      },

      /**
       * Reference to the user who referred this user
       * - Applicable only for RENTER role
       * - Can reference Admin or Agent
       */
      referredBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        index: true,
      },

      /**
       * Role of the referrer (admin or agent)
       * - Helps determine registration flow behavior
       * - Used for analytics and commission tracking
       */
      referredByRole: {
        type: String,
        enum: [ROLES.ADMIN, ROLES.AGENT],
      },

      /**
       * Indicates if password was auto-generated
       * - True: Password generated by system (Admin referral)
       * - False/Undefined: User created own password
       */
      passwordAutoGenerated: {
        type: Boolean,
        default: false,
      },

      /**
       * Timestamp when user first used their referral link
       * - For Admin/Agent analytics
       * - Tracks referral link effectiveness
       */
      firstReferralUsedAt: {
        type: Date,
      },

      /**
       * Count of successful referrals
       * - Only for Admin/Agent roles
       * - Incremented when referred user completes registration
       */
      totalReferrals: {
        type: Number,
        default: 0,
        min: 0,
      },

      // ============================================
      // EMAIL VERIFICATION
      // ============================================

      emailVerified: {
        type: Boolean,
        default: false,
        index: true,
      },
      emailVerificationToken: {
        type: String,
        select: false,
      },
      emailVerificationExpiresAt: {
        type: Date,
        select: false,
      },

      // ============================================
      // ACTIVITY TRACKING
      // ============================================

      lastLoginAt: {
        type: Date,
        index: true,
      },

      /**
       * Track password change requests
       * - Useful for users with auto-generated passwords
       */
      passwordChangedAt: {
        type: Date,
      },

      /**
       * Flag to force password change on next login
       * - True for users with auto-generated passwords
       */
      mustChangePassword: {
        type: Boolean,
        default: false,
      },

      // ============================================
      // SOFT DELETE
      // ============================================

      isDeleted: {
        type: Boolean,
        default: false,
        index: true,
      },
      deletedAt: {
        type: Date,
        index: true,
      },
      deletedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
    }
  ),
});

// Existing indexes
userSchema.index({ email: 1, isDeleted: 1 });
userSchema.index({ role: 1, accountStatus: 1, isDeleted: 1 });
userSchema.index({ createdAt: -1, isDeleted: 1 });

// New referral-related indexes
userSchema.index({ referralCode: 1 }, { sparse: true });
userSchema.index({ referredBy: 1, referredByRole: 1 });
userSchema.index({ role: 1, totalReferrals: -1 }); // Leaderboard queries

// ============================================
// MIDDLEWARE
// ============================================

/**
 * Exclude soft-deleted users by default
 */
userSchema.pre(/^find/, function (this: Query<any, IUser>) {
  if (!this.getOptions().includeDeleted) {
    this.where({ isDeleted: false });
  }
});

/**
 * Auto-populate referredBy user details when queried
 */
userSchema.pre(/^find/, function (this: Query<any, IUser>) {
  if (this.getOptions().populateReferrer) {
    this.populate({
      path: "referredBy",
      select: "fullName email role referralCode",
    });
  }
});

// ============================================
// VIRTUAL FIELDS
// ============================================

/**
 * Generate referral link URL
 */
userSchema.virtual("referralLink").get(function (this: IUser) {
  if (!this.referralCode) return null;

  const baseUrl = env.CLIENT_URL || "https://app.rentersedge.com";
  return `${baseUrl}/register?ref=${this.referralCode}`;
});

/**
 * Check if user can generate referral codes
 */
userSchema.virtual("canRefer").get(function (this: IUser) {
  return this.role === ROLES.ADMIN || this.role === ROLES.AGENT;
});

// ============================================
// INSTANCE METHODS
// ============================================

/**
 * Check if user was referred by admin
 */
userSchema.methods.isReferredByAdmin = function (this: IUser): boolean {
  return this.referredByRole === ROLES.ADMIN;
};

/**
 * Check if user was referred by agent
 */
userSchema.methods.isReferredByAgent = function (this: IUser): boolean {
  return this.referredByRole === ROLES.AGENT;
};

/**
 * Check if user needs to change password
 */
userSchema.methods.needsPasswordChange = function (this: IUser): boolean {
  return this.passwordAutoGenerated || this.mustChangePassword;
};

// Ensure virtuals are included in JSON
userSchema.set("toJSON", { virtuals: true });
userSchema.set("toObject", { virtuals: true });

import { env } from "@/env";
import mongoose from "mongoose";

const refreshTokenBlacklistSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    token: {
      type: String,
      required: true,
    },
    expiresAt: {
      type: Date,
      required: true,
      index: { expireAfterSeconds: 0 }, // ← Auto-delete expired tokens
    },
    reason: {
      type: String,
      enum: ["logout", "password_change", "security_incident", "admin_action"],
      default: "logout",
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

export const RefreshTokenBlacklist = mongoose.model(
  "RefreshTokenBlacklist",
  refreshTokenBlacklistSchema
);

export const User = model<IUser>("User", userSchema);
