// file: src/modules/user/user.model.ts

import { ACCOUNT_STATUS, ROLES } from "@/constants/app.constants";
import { BaseSchemaUtil } from "@/utils/base-schema.utils";
import { model, Query, Schema } from "mongoose";
import type { IUser } from "./user.interface";

const userSchema = BaseSchemaUtil.createSchema<IUser>({
  ...BaseSchemaUtil.mergeDefinitions(
    BaseSchemaUtil.emailField(true),
    BaseSchemaUtil.passwordField(),
    BaseSchemaUtil.phoneField(),
    {
      fullName: {
        type: String,
        required: true,
        trim: true,
        index: true,
      },
      role: {
        type: String,
        enum: Object.values(ROLES),
        required: true,
        index: true,
      },
      accountStatus: {
        type: String,
        enum: Object.values(ACCOUNT_STATUS),
        default: ACCOUNT_STATUS.INACTIVE,
        index: true,
      },

      profileImageUrl: {
        type: String,
        default: null,
        sparse: true,
        index: true,
      },

      referralCode: {
        type: String,
        unique: true,
        sparse: true,
        index: true,
      },

      referredBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        index: true,
      },

      referredByRole: {
        type: String,
        enum: [ROLES.ADMIN, ROLES.AGENT],
      },
      passwordAutoGenerated: {
        type: Boolean,
        default: false,
      },

      firstReferralUsedAt: {
        type: Date,
      },
      totalReferrals: {
        type: Number,
        default: 0,
        min: 0,
      },

      emailVerified: {
        type: Boolean,
        default: false,
        index: true,
      },
      emailVerificationToken: {
        type: String,
        select: false,
      },
      emailVerificationExpiresAt: {
        type: Date,
        select: false,
      },

      lastLoginAt: {
        type: Date,
        index: true,
      },
      passwordChangedAt: {
        type: Date,
      },
      mustChangePassword: {
        type: Boolean,
        default: false,
      },

      isDeleted: {
        type: Boolean,
        default: false,
        index: true,
      },
      deletedAt: {
        type: Date,
        index: true,
      },
      deletedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
    }
  ),
});

// Existing indexes
userSchema.index({ email: 1, isDeleted: 1 });
userSchema.index({ role: 1, accountStatus: 1, isDeleted: 1 });
userSchema.index({ createdAt: -1, isDeleted: 1 });

userSchema.index({ referralCode: 1 }, { sparse: true });
userSchema.index({ referredBy: 1, referredByRole: 1 });
userSchema.index({ role: 1, totalReferrals: -1 });

userSchema.pre(/^find/, function (this: Query<any, IUser>) {
  if (!this.getOptions().includeDeleted) {
    this.where({ isDeleted: false });
  }
});

/**
 * Auto-populate referredBy user details when queried
 */
userSchema.pre(/^find/, function (this: Query<any, IUser>) {
  if (this.getOptions().populateReferrer) {
    this.populate({
      path: "referredBy",
      select: "fullName email phoneNumber role referralCode",
    });
  }
});

userSchema.virtual("referralLink").get(function (this: IUser) {
  if (!this.referralCode) return null;

  const baseUrl = env.CLIENT_URL || "https://app.rentersedge.com";

  return this.role === ROLES.ADMIN
    ? `${baseUrl}/mor-team-form?ref=${this.referralCode}`
    : `${baseUrl}/signup?ref=${this.referralCode}`;
});

userSchema.virtual("canRefer").get(function (this: IUser) {
  return this.role === ROLES.ADMIN || this.role === ROLES.AGENT;
});

userSchema.methods.isReferredByAdmin = function (this: IUser): boolean {
  return this.referredByRole === ROLES.ADMIN;
};

userSchema.methods.isReferredByAgent = function (this: IUser): boolean {
  return this.referredByRole === ROLES.AGENT;
};

userSchema.methods.needsPasswordChange = function (this: IUser): boolean {
  return this.passwordAutoGenerated || this.mustChangePassword;
};

userSchema.set("toJSON", { virtuals: true });
userSchema.set("toObject", { virtuals: true });

import { env } from "@/env";
import mongoose from "mongoose";

const refreshTokenBlacklistSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    token: {
      type: String,
      required: true,
    },
    expiresAt: {
      type: Date,
      required: true,
      index: { expireAfterSeconds: 0 },
    },
    reason: {
      type: String,
      enum: ["logout", "password_change", "security_incident", "admin_action"],
      default: "logout",
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

export const RefreshTokenBlacklist = mongoose.model(
  "RefreshTokenBlacklist",
  refreshTokenBlacklistSchema
);

export const User = model<IUser>("User", userSchema);
