// file: src/modules/user/user.type.ts

import { ACCOUNT_STATUS } from "@/constants";
import type { ROLES } from "@/constants/app.constants";

/**
 * User response (safe for API responses - no sensitive data)
 * ✅ This should match what AuthService returns
 */
export type UserResponse = {
  _id: string;
  email: string;
  fullName: string;
  phone: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  accountStatus: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];
  emailVerified: boolean;
  lastLoginAt?: Date;

  // Referral fields
  referralCode?: string;
  referralLink?: string | null;
  referredBy?: string;
  referredByRole?: "Admin" | "Agent";
  totalReferrals: number;
  passwordAutoGenerated: boolean;
  mustChangePassword: boolean;

  createdAt: Date;
  updatedAt: Date;
};

/**
 * User create payload
 */
export type UserCreatePayload = {
  email: string;
  password?: string;
  fullName: string;
  phoneNumber?: string;
  phone?: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  emailVerified?: boolean;
  accountStatus?: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];

  // Referral tracking
  referredBy?: any;
  referredByRole?: "Admin" | "Agent";
  passwordAutoGenerated?: boolean;
  mustChangePassword?: boolean;
};

/**
 * User update payload
 */
export type UpdateUserPayload = {
  fullName?: string;
  phoneNumber?: string;
  phone?: string;
};

/**
 * Password change payload
 */
export type ChangePasswordPayload = {
  currentPassword: string;
  newPassword: string;
};

/**
 * Admin user update
 */
export type AdminUpdateUserPayload = {
  fullName?: string;
  phoneNumber?: string;
  phone?: string;
  email?: string;
  accountStatus?: "active" | "suspended" | "inactive" | "pending";
  role?: "admin" | "agent" | "renter";
};

/**
 * JWT Payload
 */
export type JWTPayload = {
  userId: string;
  email: string;
  role: string;
  iat?: number;
  exp?: number;
};
